//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_PLT_Support_CodeLists
    {
        public string CultureCode { get; set; }
        public string CodeType { get; set; }
        public string Code { get; set; }
        public Nullable<int> SortSequence { get; set; }
        public string Description { get; set; }
        public bool BaseCodeIndicator { get; set; }
    }
}
